# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connection.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63onnection.proto\"b\n\x17\x43onnectionPersonMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x14\n\x0c\x63ompany_name\x18\x04 \x01(\t\"v\n\x19\x43onnectionLocationMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tperson_id\x18\x02 \x01(\x05\x12\x10\n\x08latitude\x18\x03 \x01(\t\x12\x11\n\tlongitude\x18\x04 \x01(\t\x12\x15\n\rcreation_time\x18\x05 \x01(\t\"a\n\x16\x46indConnectionsMessage\x12\x11\n\tperson_id\x18\x01 \x01(\x05\x12\x12\n\nstart_date\x18\x02 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x03 \x01(\t\x12\x0e\n\x06meters\x18\x04 \x01(\x05\"k\n\x11\x43onnectionMessage\x12,\n\x08location\x18\x01 \x01(\x0b\x32\x1a.ConnectionLocationMessage\x12(\n\x06person\x18\x02 \x01(\x0b\x32\x18.ConnectionPersonMessage\"@\n\x15\x43onnectionMessageList\x12\'\n\x0b\x63onnections\x18\x01 \x03(\x0b\x32\x12.ConnectionMessage2W\n\x11\x43onnectionService\x12\x42\n\x0f\x46indConnections\x12\x17.FindConnectionsMessage\x1a\x16.ConnectionMessageListb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'connection_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONNECTIONPERSONMESSAGE._serialized_start=20
  _CONNECTIONPERSONMESSAGE._serialized_end=118
  _CONNECTIONLOCATIONMESSAGE._serialized_start=120
  _CONNECTIONLOCATIONMESSAGE._serialized_end=238
  _FINDCONNECTIONSMESSAGE._serialized_start=240
  _FINDCONNECTIONSMESSAGE._serialized_end=337
  _CONNECTIONMESSAGE._serialized_start=339
  _CONNECTIONMESSAGE._serialized_end=446
  _CONNECTIONMESSAGELIST._serialized_start=448
  _CONNECTIONMESSAGELIST._serialized_end=512
  _CONNECTIONSERVICE._serialized_start=514
  _CONNECTIONSERVICE._serialized_end=601
# @@protoc_insertion_point(module_scope)
