apiVersion: v1
kind: Service
metadata:
  labels:
    service: app
  name: app
  namespace: udaconnect
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
      nodePort: 30000
  selector:
    service: app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: app
  name: app
  namespace: udaconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      service: app
  template:
    metadata:
      namespace: udaconnect
      labels:
        service: app
    spec:
      containers:
        - image: giancarloromeo/udaconnect-app:latest
          name: app
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "64m"
            limits:
              memory: "256Mi"
              cpu: "256m"
      restartPolicy: Always
