apiVersion: v1
kind: ConfigMap
data:
  DB_USERNAME: "ct_admin"
  DB_NAME: "geoconnections"
  DB_HOST: "postgres"
  DB_PORT: "5432"

  PERSONS_SERVICE_HOST: "persons-service"
  PERSONS_SERVICE_PORT: "5005"

  CONNECTIONS_SERVICE_HOST: "connections-service"
  CONNECTIONS_SERVICE_PORT: "5005"

  LOCATIONS_SERVICE_HOST: "locations-service"
  LOCATIONS_SERVICE_PORT: "5005"
  LOCATIONS_KAFKA_TOPIC: "locations"

  KAFKA_SERVICE_HOST: "kafka-service"
  KAFKA_SERVICE_PORT: "9092"

  ZOOKEEPER_CLIENT_PORT: "2181"
  ZOOKEEPER_TICK_TIME: "2000"
  KAFKA_BROKER_ID: "1"
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-service:9092"
  KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
metadata:
  name: config
  namespace: udaconnect
