apiVersion: v1
kind: Service
metadata:
  labels:
    service: zookeeper
  name: zookeeper
  namespace: udaconnect
spec:
  ports:
    - name: "2181"
      port: 2181
  selector:
    service: zookeeper
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: zookeeper
  name: zookeeper
  namespace: udaconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      service: zookeeper
  template:
    metadata:
      labels:
        service: zookeeper
    spec:
      containers:
        - image: confluentinc/cp-zookeeper:latest
          name: zookeeper
          imagePullPolicy: Always
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: ZOOKEEPER_CLIENT_PORT
            - name: ZOOKEEPER_TICK_TIME
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: ZOOKEEPER_TICK_TIME
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: kafka-service
  name: kafka-service
  namespace: udaconnect
spec:
  ports:
    - name: "9092"
      port: 9092
  selector:
    service: kafka-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: kafka-service
  name: kafka-service
  namespace: udaconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      service: kafka-service
  template:
    metadata:
      labels:
        service: kafka-service
    spec:
      containers:
        - image: confluentinc/cp-kafka:latest
          name: kafka-service
          imagePullPolicy: Always
          env:
            - name: KAFKA_BROKER_ID
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: KAFKA_BROKER_ID
            - name: KAFKA_ZOOKEEPER_CONNECT
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: KAFKA_ZOOKEEPER_CONNECT
            - name: KAFKA_ADVERTISED_LISTENERS
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: KAFKA_ADVERTISED_LISTENERS
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: KAFKA_INTER_BROKER_LISTENER_NAME
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
      restartPolicy: Always
