apiVersion: v1
kind: Service
metadata:
  labels:
    service: persons-service
  name: persons-service
  namespace: udaconnect
spec:
  ports:
    - name: "5005"
      port: 5005
      targetPort: 5005
  selector:
    service: persons-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: persons-service
  name: persons-service
  namespace: udaconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      service: persons-service
  template:
    metadata:
      labels:
        service: persons-service
    spec:
      containers:
        - image: giancarloromeo/udaconnect-persons-service:latest
          name: persons-service
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: DB_NAME
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: DB_PORT
            - name: PERSONS_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: PERSONS_SERVICE_PORT
      restartPolicy: Always
