# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: person.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cperson.proto\"X\n\rPersonMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x14\n\x0c\x63ompany_name\x18\x04 \x01(\t\"4\n\x11PersonMessageList\x12\x1f\n\x07persons\x18\x01 \x03(\x0b\x32\x0e.PersonMessage\"#\n\x10GetPersonMessage\x12\x0f\n\x07id_list\x18\x01 \x03(\x05\"\x14\n\x12\x45mptyPersonMessage2\x9a\x01\n\rPersonService\x12(\n\x06\x43reate\x12\x0e.PersonMessage\x1a\x0e.PersonMessage\x12,\n\x03Get\x12\x11.GetPersonMessage\x1a\x12.PersonMessageList\x12\x31\n\x06GetAll\x12\x13.EmptyPersonMessage\x1a\x12.PersonMessageListb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'person_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PERSONMESSAGE._serialized_start=16
  _PERSONMESSAGE._serialized_end=104
  _PERSONMESSAGELIST._serialized_start=106
  _PERSONMESSAGELIST._serialized_end=158
  _GETPERSONMESSAGE._serialized_start=160
  _GETPERSONMESSAGE._serialized_end=195
  _EMPTYPERSONMESSAGE._serialized_start=197
  _EMPTYPERSONMESSAGE._serialized_end=217
  _PERSONSERVICE._serialized_start=220
  _PERSONSERVICE._serialized_end=374
# @@protoc_insertion_point(module_scope)
